env:
  global:
    - secure: "oL/UPKX64knAVZkBfQ7DR5XadXXIh0bY/ioXbtJb47XoivBIgUoFekrC4gq9qYabORj9PTaUpkGM2h3xtEL2n/DzILsuL+fHhKVD6WWNkj7IgtsFW616gKTC4oQ6a+F1hWbF0cxaC7M2QWwYdheSEaNO3RvhGoltKzMKwcSq9Es="
    - secure: "cc1Rl6/ga+l6Edy74Q90O3bZ4SdzKIrYPOx1NqX+yAL7uvgimmasA6cWV85TQZ9FeXkc9H+QSB7WNTVQ3sTa5aceHg0eXj79xSBOcnSKUhUttrgfjQ74+UOyWnIS3kKkkFzhG/x5YPyrw3nOUGBrt4A1xdgKPtb/P9tXjQEkVYo="

language: php

before_script:
  - composer install --dev
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=psr2 app/src
  - phpunit

after_success:
  - php vendor/bin/coveralls
  - gem install pagoda
  - echo -e "Host git.pagodabox.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-keygen -f ~/.ssh/id_rsa -N "" -t rsa -C "mike@mikefunk.com"
  - pagoda --username=$PAGODABOX_USERNAME --password=$PAGODABOX_PASSWORD key:push --file=$HOME/.ssh/id_rsa.pub
  - git remote add pagoda git@git.pagodabox.com:bookymark.git
  - git push pagoda master
  # - pagoda --username=$PAGODABOX_USERNAME --password=$PAGODABOX_PASSWORD --app=bookymark deploy
