mike_funk_bookymark_site:
    resource: "@MikeFunkBookymarkSiteBundle/Resources/config/routing.yml"
    prefix:   /

mike_funk_bookymark_bookmarks:
    resource: "@MikeFunkBookymarkBookmarksBundle/Resources/config/routing.yml"
    prefix:   /bookmarks/

