parameters:
#    mike_funk_bookymark_bookmarks.example.class: MikeFunk\Bookymark\BookmarksBundle\Example

services:
#    mike_funk_bookymark_bookmarks.example:
#        class: %mike_funk_bookymark_bookmarks.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
